[package]
name = "c_microwave_diy"
version = "0.1.0"
authors = ["William Brown <william@blackhats.net.au>"]
edition = "2018"

[build-dependencies]
cc = "1.0"

[dependencies]
microwave_common = { path = "../microwave_common" }
